### ISSUE TITLE
issueベースの開発_レビュー依頼用

### ISSUE THREAD

**Issue by taka292** [taka292/minire#37]

**Comment by taka292** [comment]
■Webアプリの概要
miniaは、ミニマリストやその志向を持つ人々が、必要なものを厳選し、
シンプルで豊かな暮らしを追求するための商品レビューサイトです。
利用者が愛用する多機能・高品質な商品を投稿し、他のユーザーと共有することで、より良い商品と出会えます。

レビューは画像付きで投稿でき、商品カテゴリーや検索機能を活用して目的の情報を簡単に探せます。
さらに、いいねやコメント、フォロー機能を通じてユーザー間の交流を促進。
購入時には、Amazonアソシエイトを利用した商品リンクからスムーズに購入が可能です。

miniaは、暮らしを豊かにするアイテムや情報を効率よく見つけることができるプラットフォームです。

■1週間辺りの開発に向けられる時間
- 1週間あたり：20時間

■ProjectsのURL
https://github.com/users/taka292/projects/2

■MVPリリースまで
- [x] rails new
- [x] 本番環境にデプロイ
- [x] トップページ
- [x]  レビュー投稿 (画像アップロード機能含む)
- [x]  レビュー一覧（未ログインでも閲覧可能）
- [x]  レビュー詳細（未ログインでも閲覧可能）
- [x]  レビュー更新
- [x]  レビュー削除
- [x]  コメント機能（非 ajax）
- [x]  投稿履歴
- [x]  いいね
- [x]  検索機能（未ログインでも閲覧可能）
- [x]  プロフィール
- [x]  管理者ページ
- [x]  投稿商品の商品リンク登録
- [x]  会員登録 (画像アップロード機能含む)
- [x]  ログイン
- [x]  ログアウト
- [x]  お問い合わせ
- [x]  利用規約
- [x]  プライバシーポリシー
- [x] レスポンシブ対応
- [x]  RSpec（モデルテスト・システムテスト）


■MVP後
- [x] パスワードリセット
- [x] SNS ログイン
- [x] フォロー機能
- [x] レーティング（★評価）
- [x] オートコンプリート機能
- [x] 投稿ポイントシステム（バッジ）
- [x] ファビコン
- [x] OGP
- [x] コメント機能（ajax）


■MVPレビュー依頼予定日
予定日：2025年 1月 5日

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
以下、コメントになります。

--- 
#22 は
- ログイン
- ログアウト
- サインアップ
各でissueを作成した方が、より正確な工数が測れるかと思いました。（4つのタスクでストーリーポイント3は厳しい印象を持ったため）

**Comment by taka292** [comment]
コメントありがとうございます。
頂いたご指摘に関して、対応したためご確認のほどよろしくお願いします。

**Comment by beppumasaki** [comment]
概ね良いかと思います。LGTMです。
